import * as React from 'react';
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Layout from '../components/layout';
import { Avatar, Breadcrumbs, Button, CardHeader, CardMedia, Container, IconButton, Table, TableBody, TableCell, tableCellClasses, TableRow, Typography } from '@mui/material';
import Link from 'next/link';
import Head from 'next/head';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import styles from '../assets/scss/Project.module.scss';
import { red, green, grey } from '@mui/material/colors';



const drawerWidth = 240;

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    backgroundColor: theme.palette.common.black,
    color: theme.palette.common.white,
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: 14,
  },
}));

const StyledTableRow = styled(TableRow)(({ theme }) => ({
  '&:nth-of-type(odd)': {
    backgroundColor: theme.palette.action.hover,
  },
  // hide last border
  '&:last-child td, &:last-child th': {
    border: 0,
  },
}));


export default function View() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout drawerWidth={drawerWidth} />
      <main>
        <h1>Projects</h1>
        <Breadcrumbs aria-label="breadcrumb">
          <Link color="inherit" href="/" className='breadcrumb-link'>
            Dashboard
          </Link>
          <Typography color="text.primary">Projects</Typography>
        </Breadcrumbs>

        <Grid container spacing={2} className={styles.projectDetailContainer + ' mt-2'}>
          <Grid item xs={12}>
            <Card>
              <CardContent className='New'>
                <h2>PM Tool</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel elit neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum sollicitudin libero vitae est consectetur, a molestie tortor consectetur. Aenean tincidunt interdum ipsum, id pellentesque diam suscipit ut. Vivamus massa mi, fermentum eget neque eget, imperdiet tristique lectus. Proin at purus ut sem pellentesque tempor sit amet ut lectus. Sed orci augue, placerat et pretium ac, hendrerit in felis. Integer scelerisque libero non metus commodo, et hendrerit diam aliquet. Proin tincidunt porttitor ligula, a tincidunt orci pellentesque nec. Ut ultricies maximus nulla id consequat. Fusce eu consequat mi, eu euismod ligula. Aliquam porttitor neque id massa porttitor, a pretium velit vehicula. Morbi volutpat tincidunt urna, vel ullamcorper ligula fermentum at.</p>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card>
              <CardContent>
                <h3 className={styles.projectDetails}>Project details</h3>

              </CardContent>
              <Table>
                <TableBody>
                  <StyledTableRow>
                    <StyledTableCell component="th" scope="row">Cost</StyledTableCell>
                    <StyledTableCell align="right">$1245</StyledTableCell>
                  </StyledTableRow>
                  <StyledTableRow>
                    <StyledTableCell component="th" scope="row">Total Hours</StyledTableCell>
                    <StyledTableCell align="right">200 Hours</StyledTableCell>
                  </StyledTableRow>
                  <StyledTableRow>
                    <StyledTableCell component="th" scope="row">Created</StyledTableCell>
                    <StyledTableCell align="right">25 Feb, 2019</StyledTableCell>
                  </StyledTableRow>
                  <StyledTableRow>
                    <StyledTableCell component="th" scope="row">Deadline</StyledTableCell>
                    <StyledTableCell align="right">12 Jun, 2019</StyledTableCell>
                  </StyledTableRow>
                  <StyledTableRow>
                    <StyledTableCell component="th" scope="row">Status</StyledTableCell>
                    <StyledTableCell align="right">Working</StyledTableCell>
                  </StyledTableRow>
                </TableBody>
              </Table>
            </Card>
            <Button variant="contained" color="primary"  className='mt-4' fullWidth>
                Add Status
            </Button>
            <Card className='mt-4 mb-4'>
              <CardContent>
                <h3 className={styles.projectDetails}>Team</h3>
              </CardContent>

              <div className={styles.nameContainer + ' mb-2'} >
                <Avatar sx={{ bgcolor: red[500] }} aria-label="Satpal Singh">
                  S
                </Avatar>
                <span className={styles.name}>Satpal Singh</span>
              </div>
              <div className={styles.nameContainer  + ' mb-2'}>
                <Avatar sx={{ bgcolor: grey[500] }} aria-label="Harjeet Singh">
                  H
                </Avatar>
                <span className={styles.name}>Harjeet Singh</span>
              </div>

            </Card>
          </Grid>
        </Grid>
      </main>
    </>
  );
}