import { Container, Breadcrumbs, Grid, Paper, Typography } from '@mui/material';
import Head from 'next/head'
import Layout from './components/layout';
import { styled } from '@mui/material/styles';
import ViewInArOutlinedIcon from '@mui/icons-material/ViewInArOutlined';
import RocketLaunchOutlinedIcon from '@mui/icons-material/RocketLaunchOutlined';
import AttachMoneyOutlinedIcon from '@mui/icons-material/AttachMoneyOutlined';
import GroupsOutlinedIcon from '@mui/icons-material/GroupsOutlined';
import FeedOutlinedIcon from '@mui/icons-material/FeedOutlined';
import styles from './assets/scss/Dashboard.module.scss';

const drawerWidth = 240;

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout drawerWidth={drawerWidth} />
      <main>
        <h1>Welcome Admin!</h1>
        <Breadcrumbs aria-label="breadcrumb">
          <Typography color="text.primary">Dashboard</Typography>
        </Breadcrumbs>

        <div className='Grid mt-2'>
          <Grid container spacing={2}>
            <Grid item xs={12} md={3}>
              <Item className={styles.widgetContainer}>
                <div className={styles.widgetIcon}>
                  <RocketLaunchOutlinedIcon />
                </div>
                <div className={styles.widgetInfo}>
                  <h3>1120</h3>
                  <span>Projects</span>
                </div>
              </Item>
            </Grid>
            <Grid item xs={12} md={3}>
              <Item className={styles.widgetContainer}>
                <div className={styles.widgetIcon}>
                  <AttachMoneyOutlinedIcon />
                </div>
                <div className={styles.widgetInfo}>
                  <h3>44</h3>
                  <span>Clients</span>
                </div>
              </Item>
            </Grid>
            <Grid item xs={12} md={3}>
              <Item className={styles.widgetContainer}>
                <div className={styles.widgetIcon}>
                  <GroupsOutlinedIcon />
                </div>
                <div className={styles.widgetInfo}>
                  <h3>100</h3>
                  <span>Employees</span>
                </div>
              </Item>
            </Grid>
            <Grid item xs={12} md={3}>
              <Item className={styles.widgetContainer}>
                <div className={styles.widgetIcon}>
                  <FeedOutlinedIcon />
                </div>
                <div className={styles.widgetInfo}>
                  <h3>5</h3>
                  <span>Interviews</span>
                </div>
              </Item>
            </Grid>
          </Grid>
        </div>
      </main>
    </>
  )
}
